server:
  port: 8081
spring:
  application:
    name: provider # 应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.company.cloud.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.company.cloud.dao: debug  #sql日志打印
eureka:
  client:
    fetch-registry: false   #从注册中心拉
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka